src/views/Transaction/Nomad/Header.vue
Ethereum/Moonbeam networks were hardcoded in the notifications. We should get these programatically.
=> fix: notification networks

src/config/config.main.ts, src/config/config.types.ts, src/config/tokens.main.ts
Fixes https://sentry.io/organizations/nomad-xyz/issues/3056038299/?project=6139473&query=is%3Aunresolved in sentry
=> fix: milkomedac1 -> milkomedaC1 to match sdk domain name

src/services/sentry.ts
=> feat: add ability to silence errors

CHANGELOG.md, package-lock.json, package.json, src/store/modules/connext.ts
Need additional logs to see what error is thrown from connext when errors occur.
=> chore: update connext package, log error thrown from connext to console

CHANGELOG.md, src/config/config.main.ts
=> update: moonbeam explorer url

CHANGELOG.md, package-lock.json, package.json, src/views/Transfer/Review/Review.main.vue
=> fix: access destinationAddress property correctly

src/views/Transfer/Input/Input.amount.vue
#109 
Functionality is there
TODO:
https://user-images.githubusercontent.com/36751902/163229460-c6ad8dd2-464d-41b7-a039-06c34e153ecc.mov
=> feature: max button for ERC-20 tokens

public/index.html
Julian wants to try something else
=> delete: zendesk widget

CHANGELOG.md, package.json, src/store/modules/userInput.ts, src/views/Transfer/Input/Input.inputs.vue
=> fix: add more validations and checks around network selection

CHANGELOG.md, package.json, yarn.lock
bump sdk bridge for new dev deploy
=> bump: sdk-bridge

src/views/Transaction/Nomad/Details.vue
Closes #288 
Context:
Sometimes users navigate to the transaction page and input the wrong details but the page looks like it's just loading.  Should provider helpful error messages so users can get the right url params
=> add: error handling for tx details page

src/views/Transaction/Nomad/Details.vue, src/views/Transaction/Nomad/Header.vue, src/views/Transfer/Review/Review.main.vue
Status 4 in indexer indicates processed, used to be status 3
=> fix: status 4 is processed, update 'no fee'

src/App.vue, src/store/modules/connext.ts, src/store/modules/wallet.ts, src/utils/connext.ts, src/views/Transactions/Connext.main.vue
instantiates connext later (as part of connecting wallet)
handles cases where connext would not be instantiated yet
=> fix: instantiate Connext after wallet connect

src/App.vue, src/components/Layout/Nav.vue, src/store/modules/sdk.ts, src/store/modules/wallet.ts, src/utils/metamask.ts, src/views/Transfer/Review/Review.send.vue
Reading through the web3modal source code and [this example](https://github.com/Web3Modal/web3modal/blob/master/example/src/App.tsx) helped a lot
=> chore: remove checks for metamask installed, use web3 provider for requests

src/store/modules/wallet.ts, src/views/Transaction/Nomad/Header.vue
#300 
This is one error that looks like a gas estimation error, but is actually due to being already processed
=> fix: show helpful error message to users

CHANGELOG.md, package.json, src/utils/index.ts, src/views/Transfer/Input/Input.amount.vue
`.toFixed()` rounds up.  Used logic from `toDecimals` to truncate after 6th decimal
=> fix: rounding error

package.json, src/config/tokenIdentifiers.ts, src/config/tokens.ts, yarn.lock
Need to show evmostestnet on staging gui
=> feat: update configuration from v0.1.0-rc.18 -> v0.1.0-rc.23

src/views/Transaction/Nomad/Details.vue, src/views/Transaction/Nomad/Header.vue
When I made update to handle indexer downtime, I messed up the loading state
=> fix: show loading state

src/components/NotificationError.vue, src/config/tokenIdentifiers.ts, src/views/TermsModal.vue, src/views/TermsOfUse.vue, src/views/Transaction/Nomad/Details.vue, src/views/Transaction/Nomad/Header.vue, src/views/Transfer/Review/Review.main.vue, vue.config.js
- converts token address from bytes32 for ui display
- lints
=> fix: token addr display

package.json, yarn.lock
=> Imti/bump configuration v0.1.0 rc.24

src/App.vue, src/components/NetworkAlert.vue, src/views/Transaction/Nomad/Details.vue
- Takes down moonbeam banner
- Moves network-specific alert logic to `NetworkAlert` component
=> remove banner, create network alert component

src/App.vue
=> add: sentry user id

src/config/tokens.ts
=> fix: hide avax tokens

src/components/Layout/Footer.vue
=> add: forum link

src/components/Breadcrumb.vue, src/views/Transfer/Input/Input.main.vue, src/views/Transfer/Review/Review.main.vue
#206 
- add queries for destination and token `?destination=goerli&token=USDC`
- fix breadcrumb click
- fix missing transfer-steps not registered on component
=> add: dest param

CHANGELOG.md, package.json, src/views/Transfer/Review/Review.main.vue
- update version/changelog
- fix minor alert annoyance
=> fix: only show warning if user keeps connext selected

src/views/Transfer/Input/Input.tokens.vue
=> style: token switch network button

src/App.vue, src/components/NetworkAlert.vue
=> hotfix: moonbeam maintenance mode banner

src/config/tokenIdentifiers.ts, src/store/modules/sdk.ts, src/utils/nomadAPI.ts, src/views/Transactions/Nomad/Nomad.main.vue, src/views/Transactions/Nomad/columns/amount.vue, src/views/Transactions/Nomad/columns/transaction.vue, src/views/Transfer/Transfer.main.vue
- Filter for supported networks
- Get txs where recipient or sender are a match
- Change page size to 5
- Fix updated field names (tx -> dispatchTx)
=> fix: dev history

src/config/tokens.ts, src/config/types.ts, src/store/modules/wallet.ts, src/store/mutation-types.ts, src/views/Transfer/Input/Input.tokens.vue, src/views/Transfer/Transfer.main.vue
Prepare development for release to prod.  Remove token list model (save branch `feature/add-tokens` for later reference)
=> refactor: remove token list model

src/store/modules/wallet.ts
Was showing up on Moonbeam and another network (can't remember) when using WalletConnect.  Prevented user from bridging
=> fix: pollingBlockTracker error

src/config/tokenIdentifiers.ts, src/config/tokens.ts
Token migration is complete. No need to keep these displayed in GUI anymore
=> remove: C3, CARDS, and GERO tokens

src/views/Transaction/Nomad/Header.vue
If 1 hour past confirmation time, allow user to process manually
=> feature: allow manual processing for stale transactions
